name: Staging

# Controls when the workflow will run
on:
  pull_request:

jobs:
   test-flash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests on flash"
      - name: Run CI/CD tests on flash
        uses: akto-api-security/run-scan@v1.0.12
        with:
          AKTO_DASHBOARD_URL: https://flash.staging.akto.io
          GITHUB_COMMIT_ID: ${{github.event.pull_request.head.sha}}
          AKTO_API_KEY: ${{secrets.AKTO_API_KEY_FLASH}}
          AKTO_TEST_ID: ${{vars.FLASH_TEST_ID}}
          OVERRIDDEN_TEST_APP_URL: example.com
